### ISSUE TITLE
Updates on Job Board UI data provider functionalities

### ISSUE THREAD

**Issue by saminur** [smarota17/JobTracker#17]
The methods had minor bugs in the code. 

Fixing the issues accordingly

**Comment by smarota17** [comment]
Can you leave a detailed summary of what bugs you encountered and how you fixed them?

**Comment by saminur** [comment]
The Job Board UI is using Job Class. But the methods on Job data provider class and UI forms had different field information in the methods like job name. Just removed those unnecessary fields to fix the bugs for job board UI

**Comment by smarota17** [comment]
Sounds good! Closing the issue.
