### ISSUE TITLE
Bug: When a new user is created and doesn't have any applications in their CSV file, the "My Application" page crashes. 

### ISSUE THREAD

**Issue by smarota17** [smarota17/JobTracker#46]
I tried to replicate this bug and the bug still persisted. When I manually add job objects to the user's CSV file, the page loads correctly. Need to add some sort of check that states if a user doesn't have any jobs, an empty grid loads.

**Comment by smarota17** [comment]
The bug was fixed in the FrontendDataLinking branch. Could someone review the PR and let me know if the issue persists on your end?

**Comment by saminur** [comment]
The issue persisted on loading the user file when the user name has space which will obviously be the case when someone creates a user account form them. 
c9d17a4d713534cb14b824b381b88fc3f4beb763
Please check the commit made on the job-controller branch and let me know your reviews.

**Comment by saminur** [comment]
This issue was also for creating a new Job application for the user. mainly solved by removing unnecessary spaces in username and finding the exact path for the user CSV file.

caa755ceb42ce3c817c9ba4cb791034ca318ee1c
